# docker-compose.yml

version: '3.8'

services:
  # The Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  # The Frontend Service
  frontend:
    build:
      context: ./dash-slider-auth-main
      dockerfile: Dockerfile
    ports:
      - "3000:80"